-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  author text NOT NULL,
  title text NOT NULL,
  rating NUMERIC NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (author, title, rating)
values
  ('Brian Eng', 'Computer Racing', '10'),
  ('Kristen Doucette', 'Taming Dragons', '9'),
  ('Jenny Doucette', 'Party Town', '10'),
  ('Siris Black', 'Darkly', '7'),
  ('Tamora Pierc', 'Small one', '4'),
  ('Morgan Charles', 'The Great Mountain', '10'),
  ('Darius Smoke', 'Exhale', '3'),
  ('Sarah Star', 'Cosmos', '9'),
  ('Tora Smiles', 'Love Apart', '9'),
  ('Ted Eng', 'A Cats Life', '10');

